### ISSUE TITLE
typo in readme: MyTableHeader -> MyTableHeaderCell

### ISSUE THREAD

**Issue by pknipp** [CharlesStover/react-innertext#16]
Unless I am mistaken, there is a tag-mismatch in the function definition for the MyTableHeader component in the "Real World Example".  In that definition, the close tag should be </MyTableHeaderCell>, not </MyTableHeader>.

**Comment by quisido** [comment]
Thank you. This is fixed in the repo's README. :)

This change likely won't be reflected on the NPM README.

**Comment by pknipp** [comment]
U r quite welcome.
